import Button from './component/Button'
import Navbar from './component/Navbar'
import './globals.css'


export const metadata = {
  title: 'Stravinsky',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white'>
        <Navbar />
        {children}
        <div className='flex items-center justify-center h-screen'>
        <Button/>
        </div>
      </body>
    </html>
  )
}
