import { Inter } from 'next/font/google'
import Page from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stravinsky',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <Page/>
  )
}
