import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stravinsky',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <Navbar />
  )
}
